### ISSUE TITLE
Recording of presentation

### ISSUE THREAD

**Issue by GaryWMN** [NickSalkowski/HALICON_2015_Reporting_Presentation#1]
@NickSalkowski , 
Is there a recording of the presentation associated with this code? Some colleagues saw it at Halicon and recommended it. I understand that MinneAnalytics did not record it. Have you presented anywhere else?
Thanks!

**Comment by NickSalkowski** [comment]
It wasn't recorded at MinneAnalytics HALICON 2015, and I haven't presented it anywhere else, yet.

**Comment by GaryWMN** [comment]
Okay. Thanks. For what it's worth, I'll be interested in seeing this presentation the next time it is available.

**Comment by NickSalkowski** [comment]
Thanks!
